name: Manual Command Execution

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Nmap 扫描目标 (域名或 IP)'
        required: true
        default: 'example.com'
        type: string

jobs:
  run-commands:
    name: Run custom commands
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install nmap
      run: |
        sudo apt update
        sudo apt install -y nmap

    - name: Run nmap scan
      run: |
        echo "开始扫描目标: ${{ github.event.inputs.target }}"
        nmap "${{ github.event.inputs.target }}"
