name: Custom Command Execution

on:
  workflow_dispatch:
    inputs:
      packages:
        description: '要安装的软件包 (用空格分隔多个包，如: nmap curl wget)'
        required: false
        default: 'nmap'
        type: string
      command1:
        description: '第一个要运行的命令'
        required: true
        default: 'nmap -A example.com'
        type: string
      command2:
        description: '第二个要运行的命令 (可选)'
        required: false
        default: ''
        type: string

jobs:
  run-commands:
    name: Run custom commands
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update package list
      run: sudo apt update

    - name: Install custom packages
      if: ${{ github.event.inputs.packages != '' }}
      run: |
        echo "正在安装软件包: ${{ github.event.inputs.packages }}"
        sudo apt install -y ${{ github.event.inputs.packages }}

    - name: Run first custom command
      if: ${{ github.event.inputs.command1 != '' }}
      run: ${{ github.event.inputs.command1 }}

    - name: Run second custom command
      if: ${{ github.event.inputs.command2 != '' }}
      run: ${{ github.event.inputs.command2 }}
